<a href="https://colab.research.google.com/github/NahuelRepetto/Programacion-Concurrente/blob/main/TrabajoN1Parte2Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
%%writefile Matrices.py
import sys
import random
import numpy
import threading

MAX_DIMENSION = 20
MIN_DIMENSION = 5
MAX_VALOR = 32
MIN_VALOR = -32

def inicializarMatriz(dimension, min, max):
  valores = []
  for i in range(dimension*dimension):
    valores.append(random.randint(min, max))
  return numpy.array(valores).reshape(dimension,dimension)

def calcularProducto(dimension, fila, matrizA, matrizB, matrizC):
  for i in range(dimension):
    for j in range(dimension):    
      matrizC[fila][i] += matrizA[fila][j] * matrizB[j][i]       

def mostrarMatriz(matriz, nombre):
  print("\nMatriz %s:" %nombre)
  print(matriz)

def compararMatricesCuadradas(dimension, matrizA, matrizB):      
  for i in range(dimension):
    for j in range(dimension):    
      if matrizA[i][j] != matrizB[i][j]:       
        print("\nLas matrices no son iguales, se encontro una diferencia en la posicion [%d][%d]" %(i,j))          
        return               
  print("\nLas matrices son iguales !!!") 

#VERIFICO QUE SE HAYA ENVIADO EL NUMERO DE FILAS/COLUMNAS
if len(sys.argv) < 2: 
  sys.exit("Debe ingresar el numero de filas/columnas, dentro del rango de %i a %i." %(MIN_DIMENSION, MAX_DIMENSION))

n = int(sys.argv[1]); #DIMENSIN DE LA MATRIZ 

#VERIFICO QUE SE HAYA ENVIADO EL NUMERO DENTRO DE LOS LIMITES ESTABLECIDOS
if n < MIN_DIMENSION or n > MAX_DIMENSION:
  sys.exit("El numero de filas/columnas debe estar dentro del rango de %i a %i." %(MIN_DIMENSION, MAX_DIMENSION)) 

#INICIALIZO LAS MATRICES, A Y B CON VALORES RANDOM, CS Y CH EN 0
A = inicializarMatriz(n, MIN_VALOR, MAX_VALOR)
B = inicializarMatriz(n, MIN_VALOR, MAX_VALOR)
CS = inicializarMatriz(n, 0, 0)
CH = inicializarMatriz(n, 0, 0)

#CALCULO VALORES DE CS (SECUENCIAL)
for i in range(n):
  calcularProducto(n, i, A, B, CS)  

#CALCULO VALORES DE CH (CON CONCURRENCIA)
#CREO UN VECTOR PARA ALMACENAR LAS REFERENCIAS A LOS HILOS CREADOS
hilos = []

#CREO N HILOS
for i in range(n):   
  hilos.append(threading.Thread( target=calcularProducto, args=(n, i, A, B, CH,) ))                 

#INICIO A LOS N HILOS
for i in range(n):   
  hilos[i].start() 

#ESPERO A LOS N HILOS 
for i in range(n): 
  hilos[i].join();

#MUESTRO LOS RESULTADOS
mostrarMatriz(A, "A");  
mostrarMatriz(B, "B");  
mostrarMatriz(CS, "CS");  
mostrarMatriz(CH, "CH"); 

#COMPARO CS Y CH
compararMatricesCuadradas(n, CS, CH);

Overwriting Matrices.py


In [15]:
!python Matrices.py 5


Matriz A:
[[ 17 -24 -22  22 -30]
 [-22  10 -11 -12   5]
 [-15   5  25  27  29]
 [ 20  26  28   5  12]
 [  5  -1 -32  10  31]]

Matriz B:
[[ 28 -17  30 -12 -18]
 [ 23  32  25  -4  29]
 [-12  18  17 -23  17]
 [-30  -5 -14  22 -14]
 [ 17  22   3   6   2]]

Matriz CS:
[[ -982 -2223  -862   702 -1744]
 [  191   666  -414   243   677]
 [ -922  1368  -191   353   520]
 [  876  1235  1692  -806   824]
 [  728   -61  -466  1086  -741]]

Matriz CH:
[[ -982 -2223  -862   702 -1744]
 [  191   666  -414   243   677]
 [ -922  1368  -191   353   520]
 [  876  1235  1692  -806   824]
 [  728   -61  -466  1086  -741]]

Las matrices son iguales !!!
