<a href="https://colab.research.google.com/github/NahuelRepetto/Programacion-Concurrente/blob/main/TrabajoN1Parte2Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [122]:
%%writefile Matrices.py
import sys
import random
import numpy
import threading

MAX_DIMENSION = 20
MIN_DIMENSION = 5
MAX_VALOR = 32
MIN_VALOR = -32

def inicializarMatriz(dimension, min, max):
  valores = []
  for i in range(dimension*dimension):
    valores.append(random.randint(min, max))
  return numpy.array(valores).reshape(dimension,dimension)

def calcularProducto(dimension, fila, matrizA, matrizB, matrizC):
  for i in range(dimension):
    for j in range(dimension):    
      matrizC[fila][i] += matrizA[fila][j] * matrizB[j][i]       

def mostrarMatriz(matriz, nombre):
  print("\nMatriz %s:" %nombre)
  print(matriz)

#VERIFICO QUE SE HAYA ENVIADO EL NUMERO DE FILAS/COLUMNAS
if len(sys.argv) < 2: 
  sys.exit("Debe ingresar el numero de filas/columnas, dentro del rango de %i a %i." %(MIN_DIMENSION, MAX_DIMENSION))

n = int(sys.argv[1]); #DIMENSIN DE LA MATRIZ 

#VERIFICO QUE SE HAYA ENVIADO EL NUMERO DENTRO DE LOS LIMITES ESTABLECIDOS
if n < MIN_DIMENSION or n > MAX_DIMENSION:
  sys.exit("El numero de filas/columnas debe estar dentro del rango de %i a %i." %(MIN_DIMENSION, MAX_DIMENSION)) 

#INICIALIZO LAS MATRICES, A Y B CON VALORES RANDOM, CS Y CH EN 0
A = inicializarMatriz(n, MIN_VALOR, MAX_VALOR)
B = inicializarMatriz(n, MIN_VALOR, MAX_VALOR)
CS = inicializarMatriz(n, 0, 0)
CH = inicializarMatriz(n, 0, 0)

#CALCULO VALORES DE CS (SECUENCIAL)
for i in range(n):
  calcularProducto(n, i, A, B, CS)  

#CALCULO VALORES DE CH (CON CONCURRENCIA)
#CREO UN VECTOR PARA ALMACENAR LAS REFERENCIAS A LOS HILOS CREADOS
hilos = []

#CREO N HILOS
for i in range(n):   
  hilos.append(threading.Thread( target=calcularProducto, args=(n, i, A, B, CH,) ))                 

#INICIO A LOS N HILOS
for i in range(n):   
  hilos[i].start() 

#ESPERO A LOS N HILOS 
for i in range(n): 
  hilos[i].join();

#MUESTRO LOS RESULTADOS
mostrarMatriz(A, "A");  
mostrarMatriz(B, "B");  
mostrarMatriz(CS, "CS");  
mostrarMatriz(CH, "CH"); 

Overwriting Matrices.py


In [129]:
!python Matrices.py 5


Matriz A:
[[-26 -29  -8  16  -8]
 [ 27  14 -27  -9   3]
 [ 31 -18  22  17 -31]
 [-11 -12 -23 -26  28]
 [  0  -3  30  -4 -16]]

Matriz B:
[[  1 -32 -21  10  20]
 [-13  19  25  30 -30]
 [-19  -5  26   8   3]
 [ -2  21  29  11  23]
 [-19   5 -21   6  30]]

Matriz CS:
[[  623   617   245 -1066   454]
 [  319  -637 -1243   393   -78]
 [  402 -1242   615   -53   687]
 [  102  -167 -2009  -772   313]
 [ -219  -371   925    10  -392]]

Matriz CH:
[[  623   617   245 -1066   454]
 [  319  -637 -1243   393   -78]
 [  402 -1242   615   -53   687]
 [  102  -167 -2009  -772   313]
 [ -219  -371   925    10  -392]]
